/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // La sidebar principal se auto-genera a partir de la estructura de carpetas docs/
  // Docusaurus infiere las categorías desde los archivos _category_.json
  ayudaSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

export default sidebars;
